export const Types = {
    CartService : {
        ADD_PRODUCT: "ADD_PRODUCT",
        DELETE_PRODUCT: "DELETE_PRODUCT",
        INCREASE_QUATITY: "INCREASE_QUANTITY",
        DECREASE_QUANTITY: "DECREASE_QUANTITY",
        DELETE_ALL: "DELETE_ALL"
    }
}
